

# This file was *autogenerated* from the file primegen.sage
from sage.all_cmdline import *   # import sage library

_sage_const_3 = Integer(3); _sage_const_1 = Integer(1); _sage_const_2 = Integer(2); _sage_const_0 = Integer(0)
import sys
from random import randint

if len(sys.argv) < _sage_const_3  : exit()

n = int(sys.argv[_sage_const_1 ])
ell = int(sys.argv[_sage_const_2 ])

two_factor = _sage_const_2 **(floor(n))
f_len = floor(log(_sage_const_2 **(floor(n))/ell,_sage_const_2 ))

p = _sage_const_0 
while True:
    f = randint(_sage_const_2 **f_len, _sage_const_2 **(f_len + _sage_const_1 ))
    p = two_factor * ell * f - _sage_const_1 
    if p.is_prime() : break

print(p)
print((p+_sage_const_1 ).factor())

